name: ai_personal_teacher
description: AI Personal Teacher - Class Wise Digital Teacher
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Gemini AI
  google_generative_ai: ^0.4.7

  # Voice Input
  speech_to_text: ^7.4.0

  # Voice Output
  flutter_tts: ^4.2.5

  # Image Selection
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
